public with sharing class Utils {
    public static final String FirstName = 'First_name__c';
    public static final String LastName = 'Last_name__c';
    public static final String Email = 'Email__c';
    public static final String City = 'City__c';
    public static final String INTERNAL_STATUS = 'Internal';
    public static final String INTEGRATED_STATUS = 'Integrated';
    public static final String EXTERNAL_STATUS = 'External';
}